# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/ntallaris/Downloads/clion-2019.1/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /home/ntallaris/Downloads/clion-2019.1/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/ntallaris/CLionProjects/GRPC_EXAMPLE

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/ntallaris/CLionProjects/GRPC_EXAMPLE

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/ntallaris/Downloads/clion-2019.1/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/ntallaris/Downloads/clion-2019.1/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ntallaris/CLionProjects/GRPC_EXAMPLE/CMakeFiles /home/ntallaris/CLionProjects/GRPC_EXAMPLE/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/ntallaris/CLionProjects/GRPC_EXAMPLE/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GRPC_EXAMPLE

# Build rule for target.
GRPC_EXAMPLE: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GRPC_EXAMPLE
.PHONY : GRPC_EXAMPLE

# fast build rule for target.
GRPC_EXAMPLE/fast:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/build
.PHONY : GRPC_EXAMPLE/fast

Debug/hexdump/hexdmp.o: Debug/hexdump/hexdmp.cpp.o

.PHONY : Debug/hexdump/hexdmp.o

# target to build an object file
Debug/hexdump/hexdmp.cpp.o:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Debug/hexdump/hexdmp.cpp.o
.PHONY : Debug/hexdump/hexdmp.cpp.o

Debug/hexdump/hexdmp.i: Debug/hexdump/hexdmp.cpp.i

.PHONY : Debug/hexdump/hexdmp.i

# target to preprocess a source file
Debug/hexdump/hexdmp.cpp.i:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Debug/hexdump/hexdmp.cpp.i
.PHONY : Debug/hexdump/hexdmp.cpp.i

Debug/hexdump/hexdmp.s: Debug/hexdump/hexdmp.cpp.s

.PHONY : Debug/hexdump/hexdmp.s

# target to generate assembly for a file
Debug/hexdump/hexdmp.cpp.s:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Debug/hexdump/hexdmp.cpp.s
.PHONY : Debug/hexdump/hexdmp.cpp.s

Debug/hexdump/ΗexDump.o: Debug/hexdump/ΗexDump.cpp.o

.PHONY : Debug/hexdump/ΗexDump.o

# target to build an object file
Debug/hexdump/ΗexDump.cpp.o:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Debug/hexdump/ΗexDump.cpp.o
.PHONY : Debug/hexdump/ΗexDump.cpp.o

Debug/hexdump/ΗexDump.i: Debug/hexdump/ΗexDump.cpp.i

.PHONY : Debug/hexdump/ΗexDump.i

# target to preprocess a source file
Debug/hexdump/ΗexDump.cpp.i:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Debug/hexdump/ΗexDump.cpp.i
.PHONY : Debug/hexdump/ΗexDump.cpp.i

Debug/hexdump/ΗexDump.s: Debug/hexdump/ΗexDump.cpp.s

.PHONY : Debug/hexdump/ΗexDump.s

# target to generate assembly for a file
Debug/hexdump/ΗexDump.cpp.s:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Debug/hexdump/ΗexDump.cpp.s
.PHONY : Debug/hexdump/ΗexDump.cpp.s

Driver/Driver.o: Driver/Driver.cpp.o

.PHONY : Driver/Driver.o

# target to build an object file
Driver/Driver.cpp.o:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Driver/Driver.cpp.o
.PHONY : Driver/Driver.cpp.o

Driver/Driver.i: Driver/Driver.cpp.i

.PHONY : Driver/Driver.i

# target to preprocess a source file
Driver/Driver.cpp.i:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Driver/Driver.cpp.i
.PHONY : Driver/Driver.cpp.i

Driver/Driver.s: Driver/Driver.cpp.s

.PHONY : Driver/Driver.s

# target to generate assembly for a file
Driver/Driver.cpp.s:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Driver/Driver.cpp.s
.PHONY : Driver/Driver.cpp.s

Recipe/RecipeItem/RecipeItem.o: Recipe/RecipeItem/RecipeItem.cpp.o

.PHONY : Recipe/RecipeItem/RecipeItem.o

# target to build an object file
Recipe/RecipeItem/RecipeItem.cpp.o:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Recipe/RecipeItem/RecipeItem.cpp.o
.PHONY : Recipe/RecipeItem/RecipeItem.cpp.o

Recipe/RecipeItem/RecipeItem.i: Recipe/RecipeItem/RecipeItem.cpp.i

.PHONY : Recipe/RecipeItem/RecipeItem.i

# target to preprocess a source file
Recipe/RecipeItem/RecipeItem.cpp.i:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Recipe/RecipeItem/RecipeItem.cpp.i
.PHONY : Recipe/RecipeItem/RecipeItem.cpp.i

Recipe/RecipeItem/RecipeItem.s: Recipe/RecipeItem/RecipeItem.cpp.s

.PHONY : Recipe/RecipeItem/RecipeItem.s

# target to generate assembly for a file
Recipe/RecipeItem/RecipeItem.cpp.s:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Recipe/RecipeItem/RecipeItem.cpp.s
.PHONY : Recipe/RecipeItem/RecipeItem.cpp.s

Recipe/RecipeVector/RecipeVector.o: Recipe/RecipeVector/RecipeVector.cpp.o

.PHONY : Recipe/RecipeVector/RecipeVector.o

# target to build an object file
Recipe/RecipeVector/RecipeVector.cpp.o:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Recipe/RecipeVector/RecipeVector.cpp.o
.PHONY : Recipe/RecipeVector/RecipeVector.cpp.o

Recipe/RecipeVector/RecipeVector.i: Recipe/RecipeVector/RecipeVector.cpp.i

.PHONY : Recipe/RecipeVector/RecipeVector.i

# target to preprocess a source file
Recipe/RecipeVector/RecipeVector.cpp.i:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Recipe/RecipeVector/RecipeVector.cpp.i
.PHONY : Recipe/RecipeVector/RecipeVector.cpp.i

Recipe/RecipeVector/RecipeVector.s: Recipe/RecipeVector/RecipeVector.cpp.s

.PHONY : Recipe/RecipeVector/RecipeVector.s

# target to generate assembly for a file
Recipe/RecipeVector/RecipeVector.cpp.s:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Recipe/RecipeVector/RecipeVector.cpp.s
.PHONY : Recipe/RecipeVector/RecipeVector.cpp.s

Server/CallData.o: Server/CallData.cpp.o

.PHONY : Server/CallData.o

# target to build an object file
Server/CallData.cpp.o:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Server/CallData.cpp.o
.PHONY : Server/CallData.cpp.o

Server/CallData.i: Server/CallData.cpp.i

.PHONY : Server/CallData.i

# target to preprocess a source file
Server/CallData.cpp.i:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Server/CallData.cpp.i
.PHONY : Server/CallData.cpp.i

Server/CallData.s: Server/CallData.cpp.s

.PHONY : Server/CallData.s

# target to generate assembly for a file
Server/CallData.cpp.s:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Server/CallData.cpp.s
.PHONY : Server/CallData.cpp.s

Server/ClientPacket.o: Server/ClientPacket.cpp.o

.PHONY : Server/ClientPacket.o

# target to build an object file
Server/ClientPacket.cpp.o:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Server/ClientPacket.cpp.o
.PHONY : Server/ClientPacket.cpp.o

Server/ClientPacket.i: Server/ClientPacket.cpp.i

.PHONY : Server/ClientPacket.i

# target to preprocess a source file
Server/ClientPacket.cpp.i:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Server/ClientPacket.cpp.i
.PHONY : Server/ClientPacket.cpp.i

Server/ClientPacket.s: Server/ClientPacket.cpp.s

.PHONY : Server/ClientPacket.s

# target to generate assembly for a file
Server/ClientPacket.cpp.s:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Server/ClientPacket.cpp.s
.PHONY : Server/ClientPacket.cpp.s

Server/Server.o: Server/Server.cpp.o

.PHONY : Server/Server.o

# target to build an object file
Server/Server.cpp.o:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Server/Server.cpp.o
.PHONY : Server/Server.cpp.o

Server/Server.i: Server/Server.cpp.i

.PHONY : Server/Server.i

# target to preprocess a source file
Server/Server.cpp.i:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Server/Server.cpp.i
.PHONY : Server/Server.cpp.i

Server/Server.s: Server/Server.cpp.s

.PHONY : Server/Server.s

# target to generate assembly for a file
Server/Server.cpp.s:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/Server/Server.cpp.s
.PHONY : Server/Server.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/main.cpp.s
.PHONY : main.cpp.s

sendData.grpc.pb.o: sendData.grpc.pb.cc.o

.PHONY : sendData.grpc.pb.o

# target to build an object file
sendData.grpc.pb.cc.o:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/sendData.grpc.pb.cc.o
.PHONY : sendData.grpc.pb.cc.o

sendData.grpc.pb.i: sendData.grpc.pb.cc.i

.PHONY : sendData.grpc.pb.i

# target to preprocess a source file
sendData.grpc.pb.cc.i:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/sendData.grpc.pb.cc.i
.PHONY : sendData.grpc.pb.cc.i

sendData.grpc.pb.s: sendData.grpc.pb.cc.s

.PHONY : sendData.grpc.pb.s

# target to generate assembly for a file
sendData.grpc.pb.cc.s:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/sendData.grpc.pb.cc.s
.PHONY : sendData.grpc.pb.cc.s

sendData.pb.o: sendData.pb.cc.o

.PHONY : sendData.pb.o

# target to build an object file
sendData.pb.cc.o:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/sendData.pb.cc.o
.PHONY : sendData.pb.cc.o

sendData.pb.i: sendData.pb.cc.i

.PHONY : sendData.pb.i

# target to preprocess a source file
sendData.pb.cc.i:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/sendData.pb.cc.i
.PHONY : sendData.pb.cc.i

sendData.pb.s: sendData.pb.cc.s

.PHONY : sendData.pb.s

# target to generate assembly for a file
sendData.pb.cc.s:
	$(MAKE) -f CMakeFiles/GRPC_EXAMPLE.dir/build.make CMakeFiles/GRPC_EXAMPLE.dir/sendData.pb.cc.s
.PHONY : sendData.pb.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... GRPC_EXAMPLE"
	@echo "... edit_cache"
	@echo "... Debug/hexdump/hexdmp.o"
	@echo "... Debug/hexdump/hexdmp.i"
	@echo "... Debug/hexdump/hexdmp.s"
	@echo "... Debug/hexdump/ΗexDump.o"
	@echo "... Debug/hexdump/ΗexDump.i"
	@echo "... Debug/hexdump/ΗexDump.s"
	@echo "... Driver/Driver.o"
	@echo "... Driver/Driver.i"
	@echo "... Driver/Driver.s"
	@echo "... Recipe/RecipeItem/RecipeItem.o"
	@echo "... Recipe/RecipeItem/RecipeItem.i"
	@echo "... Recipe/RecipeItem/RecipeItem.s"
	@echo "... Recipe/RecipeVector/RecipeVector.o"
	@echo "... Recipe/RecipeVector/RecipeVector.i"
	@echo "... Recipe/RecipeVector/RecipeVector.s"
	@echo "... Server/CallData.o"
	@echo "... Server/CallData.i"
	@echo "... Server/CallData.s"
	@echo "... Server/ClientPacket.o"
	@echo "... Server/ClientPacket.i"
	@echo "... Server/ClientPacket.s"
	@echo "... Server/Server.o"
	@echo "... Server/Server.i"
	@echo "... Server/Server.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... sendData.grpc.pb.o"
	@echo "... sendData.grpc.pb.i"
	@echo "... sendData.grpc.pb.s"
	@echo "... sendData.pb.o"
	@echo "... sendData.pb.i"
	@echo "... sendData.pb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

