// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: sendData.proto

#include "sendData.pb.h"
#include "sendData.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/method_handler_impl.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace sendData {

static const char* SendData_method_names[] = {
  "/sendData.SendData/sendRequest",
};

std::unique_ptr< SendData::Stub> SendData::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< SendData::Stub> stub(new SendData::Stub(channel));
  return stub;
}

SendData::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel)
  : channel_(channel), rpcmethod_sendRequest_(SendData_method_names[0], ::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status SendData::Stub::sendRequest(::grpc::ClientContext* context, const ::sendData::clientPacket& request, ::sendData::serverPacket* response) {
  return ::grpc::internal::BlockingUnaryCall(channel_.get(), rpcmethod_sendRequest_, context, request, response);
}

void SendData::Stub::experimental_async::sendRequest(::grpc::ClientContext* context, const ::sendData::clientPacket* request, ::sendData::serverPacket* response, std::function<void(::grpc::Status)> f) {
  return ::grpc::internal::CallbackUnaryCall(stub_->channel_.get(), stub_->rpcmethod_sendRequest_, context, request, response, std::move(f));
}

::grpc::ClientAsyncResponseReader< ::sendData::serverPacket>* SendData::Stub::AsyncsendRequestRaw(::grpc::ClientContext* context, const ::sendData::clientPacket& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::sendData::serverPacket>::Create(channel_.get(), cq, rpcmethod_sendRequest_, context, request, true);
}

::grpc::ClientAsyncResponseReader< ::sendData::serverPacket>* SendData::Stub::PrepareAsyncsendRequestRaw(::grpc::ClientContext* context, const ::sendData::clientPacket& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderFactory< ::sendData::serverPacket>::Create(channel_.get(), cq, rpcmethod_sendRequest_, context, request, false);
}

SendData::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      SendData_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< SendData::Service, ::sendData::clientPacket, ::sendData::serverPacket>(
          std::mem_fn(&SendData::Service::sendRequest), this)));
}

SendData::Service::~Service() {
}

::grpc::Status SendData::Service::sendRequest(::grpc::ServerContext* context, const ::sendData::clientPacket* request, ::sendData::serverPacket* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace sendData

